# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.0.10
group=net.tearpelato
java_version=25
# Common
minecraft_version=26.3
mod_name=CraftCoreLIB
mod_author=Tier1234
mod_id=craftcorelib
license=MIT
credits=
description=Built-in LIB providing useful APIS for multiloader projects.\nFeaturing Config System, NetworkBuilder, ScreenEvents handling\n and much more
minecraft_version_range=[26.1.2,)
neo_form_version=26.3-1
# Fabric
fabric_version=0.162.0+26.3
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=26.3.0.58-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
